export const works = [
  { slug: 'dragon-among-clouds', title: 'Untitled — Dragon and Clouds', year: 'Year to be confirmed', medium: 'Material and dimensions to be confirmed', image: '/media/works/dragon-among-clouds.jpg', imageAlt: 'Framed painting of a blue-green dragon moving through layered cream and brown clouds.', description: 'A dragon moves through layered clouds in a contemporary minhwa composition. Catalogue title, year, material, and dimensions are being confirmed with the artist.' },
  { slug: 'books-brushes-peonies', title: 'Untitled — Books, Brushes and Peonies', year: 'Year to be confirmed', medium: 'Material and dimensions to be confirmed', image: '/media/works/books-brushes-peonies.jpg', imageAlt: 'Framed painting of books, brushes, vessels, and pink peonies arranged in a chaekgeori still life.', description: 'A contemporary chaekgeori arrangement of books, brushes, vessels, and peonies. Catalogue title, year, material, and dimensions are being confirmed with the artist.' },
  { slug: 'chaekgeori-blue', title: 'Untitled — Chaekgeori, Blue', year: 'Year to be confirmed', medium: 'Material and dimensions to be confirmed', image: '/media/works/chaekgeori-blue.jpg', imageAlt: 'Blue and violet chaekgeori painting displayed as a vertical hanging scroll.', description: 'A blue and violet chaekgeori composition shown as a hanging scroll. Catalogue title, year, material, and dimensions are being confirmed with the artist.' },
  { slug: 'chaekgeori-red', title: 'Untitled — Chaekgeori, Red', year: 'Year to be confirmed', medium: 'Material and dimensions to be confirmed', image: '/media/works/chaekgeori-red.jpg', imageAlt: 'Red, green, and blue chaekgeori painting displayed as a vertical hanging scroll.', description: 'A warm chaekgeori composition of books, vessels, flowers, and objects, shown as a hanging scroll. Catalogue title, year, material, and dimensions are being confirmed with the artist.' },
  { slug: 'floral-vine', title: 'Untitled — Floral Vine', year: 'Year to be confirmed', medium: 'Material and dimensions to be confirmed', image: '/media/works/floral-vine.jpg', imageAlt: 'Dark painting with a pale flowering vine and patterned circular blossoms.', description: 'A pale flowering vine unfolds against a black field. Catalogue title, year, material, and dimensions are being confirmed with the artist.' },
  { slug: 'tenuta-del-buonamico', title: 'Tenuta del Buonamico', year: 'Year to be confirmed', medium: 'Commissioned printed label; details to be confirmed', image: '/media/works/tenuta-del-buonamico.jpg', imageAlt: 'Wine label featuring a blue chaekgeori illustration and the name Kim Hye Jin.', description: 'A commissioned wine-label image featuring a chaekgeori composition. Year and production details are being confirmed with the artist.' },
  { slug: 'pair-of-chaekgeori', title: 'Untitled — Pair of Chaekgeori', year: 'Year to be confirmed', medium: 'Material and dimensions to be confirmed', image: '/media/works/pair-of-chaekgeori.jpg', imageAlt: 'A wide folding screen with two chaekgeori scenes separated by gold and leopard-pattern panels.', description: 'A wide folding screen containing two chaekgeori scenes divided by gold patterned panels. Catalogue title, year, material, and dimensions are being confirmed with the artist.' },
];
